dns:
  image: devries/dnsmasq
  links:
  - mesosmaster
  - slave1
  - slave2
  - slave3
mesosmaster:
  image: redjack/mesos-master:0.21.0
  hostname: mesosmaster
  environment:
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOG_DIR=/var/log
  volumes:
    - /var/log/mesos:/var/log/mesos
  ports:
    - "5050:5050"
slave1:
  extends: 
    file: slave.yml
    service: slave
  hostname: slave1
  environment:
    - MESOS_RESOURCES=ports(*):[9200-9200,9300-9300]
  links:
   - mesosmaster
  volumes:
    - /tmp/slave1.db:/var/lib/docker/linkgraph.db
slave2:
  extends: 
    file: slave.yml
    service: slave
  hostname: slave2
  environment:
    - MESOS_RESOURCES=ports(*):[9200-9200,9300-9300]
  links:
   - mesosmaster
  volumes:
    - /tmp/slave2.db:/var/lib/docker/linkgraph.db
slave3:
  extends: 
    file: slave.yml
    service: slave
  hostname: slave3
  environment:
    - MESOS_RESOURCES=ports(*):[9200-9200,9300-9300]
  links:
   - mesosmaster
  volumes:
    - /tmp/slave3.db:/var/lib/docker/linkgraph.db
scheduler:
  image: mesos/elasticsearch-scheduler
  command: "-d -m mesosmaster -dns dns -n 3 -nn localhost"
  links:
   - mesosmaster
   - slave1
   - slave2
   - slave3
